FROM node:22-alpine

WORKDIR /usr/src/frontend

COPY ./frontend/package*.json ./

ENV PATH /usr/src/frontend/node_modules/.bin:$PATH

RUN npm install

EXPOSE ${PORT}

CMD npm start --host 0.0.0.0 --port ${PORT} --disableHostCheck true